/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_siegan_dojo_thing_Snake */

#ifndef _Included_org_siegan_dojo_thing_Snake
#define _Included_org_siegan_dojo_thing_Snake
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_siegan_dojo_thing_Snake
 * Method:    terminalRawToNormal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_siegan_dojo_thing_Snake_terminalRawToNormal
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
