/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_siegan_dojo_Run */

#ifndef _Included_org_siegan_dojo_Run
#define _Included_org_siegan_dojo_Run
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_siegan_dojo_Run
 * Method:    controlls
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_siegan_dojo_Run_controlls
  (JNIEnv *, jclass);

/*
 * Class:     org_siegan_dojo_Run
 * Method:    terminalRawToNormal
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_siegan_dojo_Run_terminalRawToNormal
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
